### ISSUE TITLE
Unusual 'Something went wrong' error with Case Feed on native Android mobile app

### ISSUE THREAD

**Issue by SanjeevGopalan** [forcedotcom/ServiceSDK-Android#79] opened 2018-08-22 06:10 UTC
We have a native Android app used for case and knowledge management which is used by external (community) users. We are using MobileSDK v6.2.0 and ServiceSDK v212.0.0. We came across an unusual error when trying to expand on the Case Feed notification. The reproduction step is as below (see the video Salesforce Bug video.zip]\ - https://github.com/forcedotcom/ServiceSDK-Android/files/2309080/Salesforce.Bug.video.zip):
1) Community Login user creates a case
2) Case gets assigned to a queue automatically and auto response is sent
3) Case agent picks up the case and finds that the case belongs to a community user
4) Case agent assigns the case to the community user
5) Community user logs in to the native app
6) Community user clicks on the case feed notification
7) System throws an error saying 'Something Went wrong'

The debug log (attached) shows that the error is arising after a number SOQL queries the last of which is on Case Feed Object and get a 'java.lang.IllegalArgumentException'. 
[salesforce-unauthenticated-to-authenticated-case-bug.txt](https://github.com/forcedotcom/ServiceSDK-Android/files/2309078/salesforce-unauthenticated-to-authenticated-case-bug.txt)

**Comment by rileymacdonald-sf** [comment] 2018-08-22 12:38
@SanjeevGopalan Thanks for raising this. Are you able to reproduce the issue using our latest release (`2.14.0`)? In the meantime please let me investigate further and I'll get back to you with more information.

**Comment by rileymacdonald-sf** [comment] 2018-08-22 13:55
@SanjeevGopalan Are you able to reproduce the issue using our sample application?

**Comment by ogenez-tu** [comment] 2018-08-23 01:06
Hi @rileymacdonald-sf, I'll be following up this issue on behalf of @SanjeevGopalan , who's unable to follow it up at this time.

Unfortunately we cannot go to production with `214.0.0` due to the issue raised here: https://github.com/forcedotcom/ServiceSDK-Android/issues/74. We still tried it for the purpose of testing this issue, which unfortunately is still occurring:

```
08-23 09:22:48.821 16803-16803/com.transurban.linktgo.staging I/Salesforce - GetCaseFeedHandler: Encountered an error:
    java.lang.IllegalArgumentException: the bind value at index 1 is null
    [net.sqlcipher.database.SQLiteProgram.bindString(SQLiteProgram.java:252)
     net.sqlcipher.database.SQLiteQuery.bindString(SQLiteQuery.java:188)
     net.sqlcipher.database.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:66)
     net.sqlcipher.database.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1867)
     net.sqlcipher.database.SQLiteDatabase.rawQuery(SQLiteDatabase.java:1785)
     com.salesforce.android.database.DatabaseStatement.upsert(DatabaseStatement.java:97)
     com.salesforce.android.cases.core.internal.local.CaseOperation.upsertActor(CaseOperation.java:608)
     com.salesforce.android.cases.core.internal.local.CaseOperation.access$700(CaseOperation.java:46)
     com.salesforce.android.cases.core.internal.local.CaseOperation$WriteCaseFeed.runOn(CaseOperation.java:174)
     com.salesforce.android.database.DatabaseWriteJob.execute(DatabaseWriteJob.java:84)
     com.salesforce.android.service.common.utilities.threading.JobQueue$JobRunner.run(JobQueue.java:120)
     java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
     java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
     java.lang.Thread.run(Thread.java:764)]
```

From what we can see, `com.salesforce.android.database.DatabaseStatement.upsert()` attempts to perform this raw query:

```
Cursor cursor = database.rawQuery("SELECT COUNT(*) FROM " + tableName + " WHERE " + whereClause, whereArgs);
```

with the following parameters

```
tableName -> Actor
whereClause -> id=?
whereArgs -> [null]
```


The `id` should be the id of the `CaseFeedModel.ActorModel` passed from `com.salesforce.android.cases.core.internal.local.CaseOperation$WriteCaseFeed.runOn()`. However it turns out that this id is `null`, which results in the above exception being thrown. Here is corresponding state of the `ActorModel` instance at the time of the call:

```
CaseCaseFeedModel.ActorModel -> 
    companyName = null
    displayName = null
    firstName = null
    id = null
    isActive = false
    isInThisCommunity = false
    lastName = null
    photo = null
    title = null
    type = "UnauthenticatedUser"
```

Hopefully the above information is enough for you to investigate. Thanks!

**Comment by ogenez-tu** [comment] 2018-08-28 05:29
Hi,

As there was some progress on another issue we raised, I just wanted to check in on this one and see if there were any updates and/or if you needed any more info from us.

Thanks a lot!

**Comment by rileymacdonald-sf** [comment] 2018-08-28 12:27
@ogenez-tu thanks for following up. We're still investigating this issue and will post any updates as soon as possible.

Thanks.

**Comment by rileymacdonald-sf** [comment] 2018-08-28 14:26
@ogenez-tu do you have guest access enabled on your org? Can you verify this issue is only reproducible using unauthenticated users?

**Comment by ogenez-tu** [comment] 2018-08-29 06:09
Hi @rileymacdonald-sf / @evanisnor,

Below are the answers to your questions:

**_Do you have community guest access enabled on your org?_**

Yes.

**_Is this issue only reproducible using unauthenticated users?_**

Yes. The issue happens consistently after a case created in "Unauthenticated" mode is updated to "Authenticated" mode and assigned to an existing contact; when that contact accesses the case via the app (i.e. CaseUI), they are presented with the error screen as shown in the video attached in this issue's first comment

**_- The chatter feed for the case you are attempting to view has comments posted within it that originate from outside of the community. What is the origin of these posts? Email, social, etc?_**

To our knowledge, the only comment in the chatter feed is an auto-response comment generated by our Service Account (it contains the case's subject/category/description). This happens consistently as long as the case is created in "Unauthenticated" mode (whether via our website, via the app before the user is authenticated in Salesforce, or even directly in Salesforce)

Hope this helps; thanks!

**Comment by evanisnor** [comment] 2018-08-29 18:41
@ogenez-tu It sounds like your org is customized for your use case. We are having a great amount of difficulty emulating this in our test environment so we can reproduce the issue. Do you have a sandbox org with similar case data that we could use to validate a fix? If so, can you send the configuration values to me via e-mail? eisnor@salesforce.com

**Comment by evanisnor** [comment] 2018-09-12 12:08
This has been fixed in the latest release.
https://github.com/forcedotcom/ServiceSDK-Android/releases/tag/214.0.2

**Closed by evanisnor** 2018-09-12 12:08 UTC
Labels: question
